### ISSUE TITLE
Startblock and endblock property on transactions API

### ISSUE THREAD

**Issue by michaelScoff** [TrustWallet/trust-wallet-backend#17]
For pagination we need to use `startBlock` as default `0`, and `endBlock` = `9999999999`

When user come back to the app, I fetch transactions from the last transaction block. 

@kolya182 would you like to tackle this?

**Comment by kolya182** [comment]
Sure, I have some ideas how to speed up fetch time. Will get back to you on a weekend.

**Comment by rip32700** [comment]
Fixed in `8f47438`
