### ISSUE TITLE
Could not parse input for contract: The returned value is not a convertible string. Cannot read property '_id' of undefined

### ISSUE THREAD

**Issue by kolya182** [TrustWallet/trust-wallet-backend#41]
Parsing yearly blocks got this error:
[Node] info: blockInDB: 231100, blockInChain: 4452694
[Node] info: processing block: 231100
[Node] error: Could not parse input for contract 0xc1D9Be24114726b5D11ed7eF85c23Ce22A083592 with error: Error: ERROR: The returned value is not a convertible string:.
[Node] error: Could not find contract by id for 0xc1D9Be24114726b5D11ed7eF85c23Ce22A083592 with error: TypeError: Cannot read property '_id' of undefined
[Node] error: Could not parse input for contract 0x2CA7b7140BDB846CA272D7392B3DD6E2dC1a6843 with error: Error: ERROR: The returned value is not a convertible string:.
[Node] error: Could not find contract by id for 0x2CA7b7140BDB846CA272D7392B3DD6E2dC1a6843 with error: TypeError: Cannot read property '_id' of undefined
[Node] error: Could not parse input for contract 0x2CA7b7140BDB846CA272D7392B3DD6E2dC1a6843 with error: Error: ERROR: The returned value is not a convertible string:.
[Node] error: Could not find contract by id for 0x2CA7b7140BDB846CA272D7392B3DD6E2dC1a6843 with error: TypeError: Cannot read property '_id' of undefined
[Node] info: processing block: 231920
[Node] info: processing block: 232740
[Node] info: processing block: 233560
[Node] info: processing block: 234380
[Node] info: processing block: 235200
[Node] error: Could not parse input for contract 0x14FEA711DCa8fCEa6bE47E14Ea1406384f18c7cc with error: Error: ERROR: The returned value is not a convertible string:.
[Node] error: Could not find contract by id for 0x14FEA711DCa8fCEa6bE47E14Ea1406384f18c7cc with error: TypeError: Cannot read property '_id' of undefined
[Node] info: processing block: 236020
[Node] error: Could not parse input for contract 0x17c7D136bDfC4371f989076bB3842be2e73C3Ec1 with error: Error: ERROR: The returned value is not a convertible string:.
[Node] error: Could not find contract by id for 0x17c7D136bDfC4371f989076bB3842be2e73C3Ec1 with error: TypeError: Cannot read property '_id' of undefined

**Comment by rip32700** [comment]
"Cannot read property '_id' of undefined" was an aftereffect of previous errors such as "ERROR: The returned value is not a convertible string"
