### ISSUE TITLE
Could not parse input for contract: with error: Error: Couldn't decode uint256 from ABI: 0x.

### ISSUE THREAD

**Issue by kolya182** [TrustWallet/trust-wallet-backend#42]
error: Could not parse input for contract 0x5f100EBe48ae9c5396DD059DD0d8f4447f12a9E0 with error: Error: Couldn't decode uint256 from ABI: 0x.
[Node] error: Could not parse input for contract 0xaB3652FD492FbB0d6b63acB742f3eD12AfBAEf52 with error: Error: Couldn't decode uint256 from ABI: 0x.
[Node] error: Could not find contract by id for 0x5f100EBe48ae9c5396DD059DD0d8f4447f12a9E0 with error: TypeError: Cannot read property '_id' of undefined
[Node] error: Could not find contract by id for 0xaB3652FD492FbB0d6b63acB742f3eD12AfBAEf52 with error: TypeError: Cannot read property '_id' of undefined
[Node] error: Could not parse input for contract 0x5f100EBe48ae9c5396DD059DD0d8f4447f12a9E0 with error: Error: Couldn't decode uint256 from ABI: 0x.
[Node] error: Could not find contract by id for 0x5f100EBe48ae9c5396DD059DD0d8f4447f12a9E0 with error: TypeError: Cannot read property '_id' of undefined

**Comment by rip32700** [comment]
due to not having correct ABI for this contract. Will be fixed soon. Functionality already available.
