### ISSUE TITLE
Doc the setup requirements

### ISSUE THREAD

**Issue by Narragansett** [TrustWallet/trust-wallet-backend#47]
Please outline the setup requirements. I deployed to Heroku and associated an mLab mongoDB instance. Still doesn't work. What is needed to get a deployment to a working state like this -
https://trust-wallet-kovan.herokuapp.com/

**Comment by michaelScoff** [comment]
Which RPC server did you use? 

@rip32700 plans to have stable version tomorrow, then we can add documentation for the setup.

**Comment by Narragansett** [comment]
Good, I can wait. I am following and wish to complete your setup without getting in the way. Thank you,

**Comment by rip32700** [comment]
@Narragansett did you specify both Env Variables? MongoDB **AND** RPC server?

**Comment by Narragansett** [comment]
Yes. 
For Mongo I set to my mLab MongoDB @Heroku
For RPC Server I use https://kovan.infura.io/<MY INFURA ACCESS TOKEN>
but no success.  Am I allowed to access their Kovan or must I really setup my own?
You have this: https://trust-wallet-kovan.herokuapp.com/
I get this: https://trust-wallet-zenzium.herokuapp.com/

**Comment by Narragansett** [comment]
All set, I added the env vars after creating MongDB instance and I mistakenly entered as MONGODB instead of MONGDB_URI. By adding post-deploy I mistyped it. Apologies

**Comment by rip32700** [comment]
@Narragansett No worries, glad it works now. And do not hesistate to ask for help if there are any issues.
