### ISSUE TITLE
Missing operation for transfer token

### ISSUE THREAD

**Issue by michaelScoff** [TrustWallet/trust-wallet-backend#49]
URL `https://api.trustwalletapp.com/transactions/0x53786a476f8b54d4ff353ce0a413d2ed212526f6f1faf24fd43521eb045f7487`

response: 
```json
{  
   "_id":"0x53786a476f8b54d4ff353ce0a413d2ed212526f6f1faf24fd43521eb045f7487",
   "blockNumber":4547616,
   "timeStamp":"1510614114",
   "nonce":5,
   "from":"0xbb210d2dcf73fa534d645761497bda3f60bf0c6f",
   "to":"0x28c8d01ff633ea9cd8fc6a451d7457889e698de6",
   "value":"0",
   "gas":"124000",
   "gasPrice":"1000000000",
   "input":"0xa9059cbb0000000000000000000000000c6f41113abb3fa62cd5c361cbfe77322d3acd820000000000000000000000000000000000000000000000000000000000000031",
   "gasUsed":"2590171",
   "operations":[  

   ],
   "addresses":[  
      "0xbb210d2dcf73fa534d645761497bda3f60bf0c6f",
      "0x28c8d01ff633ea9cd8fc6a451d7457889e698de6"
   ]
}
```

Even though this transaction has transfer token: https://etherscan.io/tx/0x53786a476f8b54d4ff353ce0a413d2ed212526f6f1faf24fd43521eb045f7487

**Comment by rip32700** [comment]
An error occurs when trying to retrieve data for this contract address with web3js:

```error: Could not parse input for contract 0x28c8d01ff633ea9cd8fc6a451d7457889e698de6 with error: Error: ERROR: The returned value is not a convertible string:.```

**Comment by michaelScoff** [comment]
We need to find a way to support such contracts `name` were missing and symbol was` byte32` format on this contract

**Comment by rip32700** [comment]
New ABIs will be dynamically added soon, should be fixed then.
